spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/test2HosDB
spring.datasource.username=root
spring.datasource.password=root
=======
#spring.datasource.url=jdbc:mysql://localhost:3306/test2HosDB
#spring.datasource.username=root
#spring.datasource.password=root
>>>>>>> b687e6716865f54e0693f1ab52ba2d1fca7d2702
spring.datasource.driver.class=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
server.port:8989
#logging.level.org.springframework:INFO
<<<<<<< HEAD
logging.level.root=INFO
=======
logging.level.root=INFO
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
>>>>>>> b687e6716865f54e0693f1ab52ba2d1fca7d2702
